CREATE TABLE "pp_account" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"user_id" varchar(64) NOT NULL,
	"account_id" varchar(256) NOT NULL,
	"provider" varchar(256) NOT NULL,
	"provider_account_id" varchar(256) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"id_token" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pp_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pp_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pp_session" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"user_id" varchar(64) NOT NULL,
	"token" varchar(256) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ip_address" varchar(256),
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "pp_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "pp_user" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"name" varchar(256),
	"email" varchar(256) NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"onboarded" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "pp_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "pp_verification" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"identifier" varchar(256) NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pp_account" ADD CONSTRAINT "pp_account_user_id_pp_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pp_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pp_session" ADD CONSTRAINT "pp_session_user_id_pp_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pp_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "pp_post" USING btree ("name");